checks:
  go: true
build:
  environment:
    go: go1.13.5
    variables:
      GO_ENV: test
      AWS_ENDPOINT: dynamo:8000
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abc123
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
  root_path: './'
filter:
  excluded_paths:
    - "*_test.go"
